### ISSUE TITLE
Wrong or MIssing Effects

### ISSUE THREAD

**Issue by Lost-Ninja** [jaredlll08/Fluxed-Trinkets#11]
I posted on the MF thread too, but figured here would be better... ;)

Using 1.0.54:

No matter which basic circuit I use (and all of the combinations I did try) I either get no effect or a negative effect.

Adv Ice = Slowness
Adv Lava, Scorching & Streaming = Sets you on fire (no visible buff)
Adv Life = No visible effect
Adv Lightning = Night Vision
Terrestrial = NV, Haste, Res & Blindness (Blindness and IIRC NV remained active even after their buff icons had expired.

**Comment by jaredlll08** [comment]
ok well, I have discontinued the mod, I was not having fun with it, sorry
