### ISSUE TITLE
topological sort error on dedicated server

### ISSUE THREAD

**Issue by kreezxil** [jaredlll08/Fluxed-Trinkets#2]
I got a topological sort error on my dedicated server with you rmod installed.

http://pastebin.com/HGcYDZed

My mods list can be found at http://www.technicpack.net/modpack/details/kreezcast-extreme.438381/

**Comment by tterrag1098** [comment]
CoFH API needs to be updated

**Comment by kreezxil** [comment]
I already have version CoFHCore-_1.7.10_3.0.0B6-32

**Comment by tterrag1098** [comment]
That was a note for jared, not you, sorry.

**Comment by UndeadZeratul** [comment]
might be easier if you ping @jaredlll08 as well.

**Comment by jaredlll08** [comment]
Nah i saw it, working on a fix, it is either that we both need to downgrade
to java 7 OR my cofh api was outdated.

**Comment by tterrag1098** [comment]
@jaredlll08 is an owner, he gets notified for all issues and comments

**Comment by Yulife** [comment]
Did you implenent the API with paint @jaredlll08 :P

**Comment by jaredlll08** [comment]
No, i used notepad

**Comment by jaredlll08** [comment]
Ok so there are 2 possible solutions to this.
1) we bith downgrade to java 7
2) i just needed to update the cofh api
