### ISSUE TITLE
dedicated server crash woot woot!

### ISSUE THREAD

**Issue by kreezxil** [jaredlll08/Fluxed-Trinkets#4]
fluxedtrinkets:Soldering_Station : Likely cause is client-side code is being called server-side

http://pastebin.com/3RXruKnL

**Comment by jaredlll08** [comment]
Fixed on my side but i cant upload the fix right now.

**Comment by kreezxil** [comment]
Whenever you get the chance, I update and add mods daily to my pack btw, so
no pressure.

**Comment by jaredlll08** [comment]
fixed and uploaded, just wait for it to be approved

**Comment by kreezxil** [comment]
That last one has been stable! :)

Cheers!!!
